---
- name: install the iperf3 rpm from a remote repo
  yum:
    name: https://iperf.fr/download/fedora/iperf3-3.1.3-1.fc24.x86_64.rpm
    state: present

- name:  run iperf3 in detached server mode
  command: /usr/bin/iperf3 -sD

- name:  run iperf3 in detached server mode
  command: ps -ef | grep iperf3
  register: process_iperf

- debug: msg="{{ process_iperf.stdout }}"
