---
- name: install the iperf3 rpm from a remote repo
  yum:
    name: https://iperf.fr/download/fedora/iperf3-3.1.3-1.fc24.x86_64.rpm
    state: present

- name:  run iperf3 in detached server mode
  command: /usr/bin/iperf3 -sD

- name:  list what processes are running
  command: ps -e -f
  register: list_run_processes

- debug: msg="{{ list_run_processes.stdout }}"

- name:  list listen/open ports
  command: netstat -l -t -n -u
  register: list_listen_ports

- debug: msg="{{ list_listen_ports.stdout }}"
