---
- name: install the iperf3 rpm from a remote repo
  yum:
    name: https://iperf.fr/download/fedora/iperf3-3.1.3-1.fc24.x86_64.rpm
    state: present

- name:  run iperf3 in detached server mode
  command: /usr/bin/iperf3 -sD

- name:  list what processes are running
  command: ps -e -f
  register: list_run_processes

- debug: msg="{{ list_run_processes.stdout_lines }}"

- name:  list listen/open ports
  command: netstat -l -t -n -u
  register: list_listen_ports

- debug: msg="{{ list_listen_ports.stdout_lines }}"

- name: Config | Firewalld to allow tcp 5201
  firewalld:
    port: 5201/tcp
    permanent: yes
    state: enabled
  register: list_firewalld

- name: Config | Firewalld to allow udp 5201
  firewalld:
    port: 5201/udp
    permanent: yes
    state: enabled
  register: list_firewallds

- debug: msg="{{ list_firewalld.stdout_lines }}"
