site_name: QuickStart Guides
nav:
    - Home: index.md
    - AWS:
      - aws/intro.md
      - Bastion Replacement Removal: aws/aws-bastion.md
    - Azure:
      - Use Cases Overview: azure/intro.md
      - Mobile User To Cloud Application Connectivity: azure/connectUser2App.md
      - Branch Application To Cloud Application Connectivity: azure/connectApp2App.md
      - Bastion Replacement Removal: azure/azure-bastion.md
      - NFN Access with Azure Stack: azure/azure-nfn.md
    - GCP:
      - Overview: gcp/intro.md
    - NetFoundry:
      - Overview: netfoundry/intro.md
      - NF Fabric: netfoundry/fabric.md
      - NF Clients: netfoundry/client.md
      - NF Gateways: netfoundry/gateway.md
    - VCPE:
      - Overview: vcpe/intro.md

# Theme Configuration
theme:
    name: material
    primary: indigo
    accent: indigo
    font:
      text: Ubuntu
      code: Ubuntu Mono
    logo: images/wide_logo.png
    language: en
    favicon: images/fav.png
    feature:
      tabs: true
# Site Customization
extra:
  social:
    - type: github
      link: https://github.com/netfoundry
    - type: twitter
      link: https://twitter.com/netfoundry
    - type: linkedin
      link: https://linkedin.com/company/netfoundry
site_dir: ../docs
# MD Extensions
markdown_extensions:
  - toc:
      permalink: "@"
      baselevel: 2
      separator: "_"
  - admonition
  - pymdownx.superfences:
      preserve_tabs: true
  - markdown_include.include:
      base_path: docs
extra_css:
  - 'extra.css'
