site_name: QuickStart Guides
nav:
    - Home: index.md
    - NetFoundry Basics:
      - Overview: netfoundry/intro.md
      - NF Fabric: netfoundry/fabric.md
      - NF Clients: netfoundry/client.md
      - NF Gateways: netfoundry/gateway.md
      - Ziti Probe: netfoundry/zitiprobe.md
    - Cloud Providers:
      - Overview: cloud/overview.md
      - AliCloud:
        - Getting Started Guide: cloud/alicloud/getting-started.md
        - User Guide: cloud/alicloud/user-guild.md
        - Remote Access Guide: cloud/alicloud/remote-access.md 
      - AWS:
        - Bastion Replacement Removal: cloud/aws/aws-bastion.md
        - Remote Access Guide: cloud/aws/remote-access.md      
      - Azure:
        - Use Cases Overview: cloud/azure/intro.md
        - Accessing Azure Stack: cloud/azure/accessing-azure-stack.md
        - Bastion Replacement Removal: cloud/azure/azure-bastion.md
        - Branch Application To Cloud Application Connectivity: cloud/azure/connectApp2App.md
        - Mobile User To Cloud Application Connectivity: cloud/azure/connectUser2App.md
        - MS Office 365 Optimize: cloud/azure/o365-optimization.md
        - Remote Access Guide: cloud/azure/remote-access.md       
      - GCP:
        - Getting Started Guide: cloud/gcp/getting-started.md
        - Remote Access Guide: cloud/gcp/remote-access.md
      - Digital Ocean:
        - Getting Stared Guide: cloud/digitalocean/getting-started.md
        - Remote Access Guide: cloud/digitalocean/remote-access.md
      - OCP:
        - Getting Started Guide: cloud/ocp/getting-started.md
        - Importing an image: cloud/ocp/image-import.md
        - Remote Access Guide: cloud/ocp/remote-access.md    
      - VCPE:
        - CPE Automation: cloud/vcpe/cpe-automation.md
        - CPE Automation (Ubuntu): cloud/vcpe/cpe-automation-ub.md
        - Remote Access Guide: cloud/vcpe/remote-access.md
    - HyperVisors:
      - Overview: hypervisor/overview.md
      - Hyper-V:
         - Getting Started: hypervisor/hyper-v/getting-started.md
      - KVM:
         - Getting Started: hypervisor/kvm/getting-started.md
      - VMware:
         - Getting Started: hypervisor/vmware/getting-started.md
      - VirtualBox:
         - Getting Started: hypervisor/virtualbox/getting-started.md
    - API:
      - Overview: api/overview.md
      - Bash:
         - Overview: api/bash/overview.md      
      - Powershell:
         - Overview: api/powershell/overview.md
         - Getting Started: api/powershell/getting-started.md
      - Python:
         - Overview: api/python/overview.md




# Theme Configuration
theme:
    name: material
    primary: indigo
    accent: indigo
    font:
      text: Ubuntu
      code: Ubuntu Mono
    logo: images/wide_logo.png
    language: en
    favicon: images/fav.png
    feature:
      tabs: true
    custom_dir: docs/custom_theme/
# Site Customization
extra:
  social:
    - type: github
      link: https://github.com/netfoundry
    - type: twitter
      link: https://twitter.com/netfoundry
    - type: linkedin
      link: https://linkedin.com/company/netfoundry
site_dir: ../docs
# MD Extensions
markdown_extensions:
  - toc:
      permalink: "@"
      baselevel: 2
      separator: "_"
  - admonition
  - pymdownx.superfences:
      preserve_tabs: true
  - markdown_include.include:
      base_path: docs
extra_css:
  - 'extra.css'
plugins:
  - search
  - pdf-export:
      enabled_if_env: ENABLE_PDF_EXPORT
